### ISSUE TITLE
Running the Python command 'A_Runner' failed

### ISSUE THREAD

**Issue by lametti** [microelly2/Animation#11]
If I try to rotate a simple pad (sketch) I got this message:

---------------------------------------------------------------------------------------------------------------------------------------------
Animation workbench activated
re init Proxy My_Manager
re init Proxy My_Rotator
[<SelectionObject>]
<group object>
My_Rotator
************************* manager run loop:0/10
It is recommended that the assembly 2 module is used with parts imported using the assembly 2 module.
This allows for part updating, parts list support, object copying (shift + assembly2 move) and also tells the solver which objects to treat as fixed.
since no objects have the fixedPosition attribute, fixing the postion of the first object in the first constraint
Running the Python command 'A_Runner' failed:
Traceback (most recent call last):
  File "C:\FreeCAD_0.16.5871_x86_dev_bin\Mod\Animation\Animation.py", line 2040, in Activated
    FreeCADGui.doCommand("tt.Proxy.run(-1)")
  File "<string>", line 1, in <module>
  File "C:\FreeCAD_0.16.5871_x86_dev_bin\Mod\Animation\Animation.py", line 1770, in run
    import assembly2solver;assembly2solver.solveConstraints(App.ActiveDocument)
  File "C:\FreeCAD_0.16.5871_x86_dev_bin\Mod\assembly2\assembly2solver.py", line 74, in solveConstraints
    constraintSystem = FixedObjectSystem( variableManager, findBaseObject(doc, objectNames) )
  File "C:\FreeCAD_0.16.5871_x86_dev_bin\Mod\assembly2\assembly2solver.py", line 56, in findBaseObject
    debugPrint( 1, 'assembly 2 solver: assigning %s a fixed position' % objectNames[0])

list index out of range

---------------------------------------------------------------------------------------------------------------------------------------------

This is reproducible on Windows 7 x64, FreeCAD 0.15 4671 (32-bit) and FreeCAD 0.16 5871 (32-bit).

Is it caused by the Assembly workbench (assembly2)?

Thanks and Best Regards,
Robert

**Comment by lametti** [comment]
It's a single user issue. Animation is working on another machine (Windows 10 x64) and on a virtual machine (Windows XP SP3 x86).
